apiVersion: v1
kind: Service
metadata:
  name: vault-sealed
spec:
  clusterIP: None
  ports:
    - name: vault
      port: 8200
      protocol: TCP
      targetPort: 8200
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
    vault-sealed: "true"
  sessionAffinity: None
  type: ClusterIP